### ISSUE TITLE
query params "after" with "searchKeyword" always return the same result

### ISSUE THREAD

**Issue by jariartes** [Kaltsoon/rate-repository-api#16]
After my app crashed during a filtered query I repeated the same query with the graphql playground and realized that the backend returns the same set of records when both "searchKeyword" and "after" parameters are included. 

Without the "searchKeyword" parameter there's no problem with pagination thus I'm boldly assuming that the fault is with the backend.

For example

query {
  repositories(
    first: 7
    orderBy: CREATED_AT 
    searchKeyword: "T"
  ) {
    edges {
      node {
...
      }
      cursor
    }
    pageInfo  {
        endCursor
        startCursor
        totalCount
        hasNextPage
      }
  }
}

in my case totalCount = 11, hasNextPage: true and the query for the next page

  repositories(
    first: 7
    after: [pageinfo endcursor here]
    orderBy: CREATED_AT 
    searchKeyword: "T"
  ) 

returns the same set of records (7) and again indicates that hasNextPage: true. That repeats ad infinitum.

Just in case this not just an incorrect query and you want more data I can provide more complete traces after I've completed the damn course.

Br,
Jari

**Comment by Kaltsoon** [comment]
Good catch! There was some issue combining the search keyword query with the pagination query. [This](https://github.com/Kaltsoon/rate-repository-api/blob/master/src/graphql/queries/repositories.js#L73) seems to fix the issue. Let me know if you have further issues with this.
