### ISSUE TITLE
Node 16 LTS fails installing sqlite3

### ISSUE THREAD

**Issue by abdalmajeed** [Kaltsoon/rate-repository-api#20]
Using the latest node 16 would fail installing sqlite3.
I had to go back to node 14 and installing multiple packages like visual studio build tools and python 2.

**Comment by Kaltsoon** [comment]
What's the error? Seems to work fine on Node 16.6.1

**Comment by abdalmajeed** [comment]
When I tried to start using SQLite a problem occurs, that it didn't find sqlite.node which is sqlite binary for node.
According to sqlite3 documentation the latest node version is 14.x, so I thought I had to downgrade to 14.x.
I think the problem was when I installed npm packages with node 16.13.0 and npm 8.1.0 there was no pre-compiled sqlite binary and I had to compile it from source.
But now I think there's a pre-built binary to use in node-pre-gyp, so the problem is solved.
