### ISSUE TITLE
no user after intialization.

### ISSUE THREAD

**Issue by sahilrajput03** [Kaltsoon/rate-repository-api#8]
kalle, elina, matti neither is saved sqlite db i guess, coz fetchAuthorization doesn't work for any of these.
Creating new user and login with that works good :+1: 
Thanks.

**Comment by Kaltsoon** [comment]
Have you run the `npm run seed:run` script? It will populate the database with test data.

**Comment by sahilrajput03** [comment]
Ok got it now! Thanks Kalle. Its all good.
